# Generated by Django 5.1.7 on 2026-01-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_verified_profile_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(max_length=6),
        ),
    ]
