# Generated by Django 5.1.7 on 2026-01-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
