# Generated by Django 5.1.7 on 2026-01-26 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_email_token_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
