# Generated by Django 5.1.7 on 2026-01-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_created_order_created_at_remove_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('mobile', 'Mobile Money'), ('card', 'Card Payment')], max_length=20),
        ),
    ]
